ARG IMAGE_VERSION=3.8-slim-buster
ARG EXTRA
ARG GOOGLE_APPLICATION_CREDENTIALS

FROM python:$IMAGE_VERSION
ARG EXTRA
ARG GOOGLE_APPLICATION_CREDENTIALS
SHELL ["/bin/bash", "-c"]

COPY $GOOGLE_APPLICATION_CREDENTIALS /google_app_credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/google_app_credentials.json

WORKDIR /dtc_de
RUN pip install --no-cache-dir -qU pip setuptools
COPY requirements.$EXTRA.txt .
RUN pip install --no-cache-dir -qr requirements.$EXTRA.txt
COPY . .
RUN if [[ -z $EXTRA ]]; then pip install -q "."; else pip install -q ".[$EXTRA]"; fi;
